POST http://localhost:3000/users
content-type: application/json

{
    "firstname": "Nicola",
    "lastname": "Lanzoni",
    "email": "lanzoni@gmail.com",
    "department": "",
    "companyRoleLevel": "manager",
    "recruitingRole": "admin"
}

###
GET http://localhost:3000/users


###
GET http://localhost:3000/request-to-hire/1

###
PATCH http://localhost:3000/request-to-hire/1
content-type: application/json
    
{
    "firstname": "Nicola",
    "lastname": "Lanzoni"
}